package com.codegym.aiplanning.common.exception;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
    VALIDATION_FAILED(HttpStatus.BAD_REQUEST),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    INVALID_GOOGLE_CREDENTIAL(HttpStatus.UNAUTHORIZED),
    INVALID_SESSION(HttpStatus.UNAUTHORIZED),
    REFRESH_IN_PROGRESS(HttpStatus.CONFLICT),
    AUTHENTICATION_REQUIRED(HttpStatus.UNAUTHORIZED),
    SESSION_EXPIRED(HttpStatus.UNAUTHORIZED),
    ACCESS_DENIED(HttpStatus.FORBIDDEN),
    GOOGLE_ACCOUNT_LINK_REQUIRED(HttpStatus.CONFLICT),
    GOOGLE_AUTH_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
    PROFILE_SETUP_REQUIRED(HttpStatus.CONFLICT),
    ROADMAP_ONBOARDING_INCOMPLETE(HttpStatus.BAD_REQUEST),
    ROADMAP_DRAFT_EXISTS(HttpStatus.CONFLICT),
    ROADMAP_ALREADY_ACTIVATED(HttpStatus.CONFLICT),
    ROADMAP_STRUCTURE_INCOMPLETE(HttpStatus.BAD_REQUEST),
    INVALID_STATUS_TRANSITION(HttpStatus.BAD_REQUEST),
    CONCURRENT_MODIFICATION(HttpStatus.CONFLICT),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND),
    CURRENT_PASSWORD_INCORRECT(HttpStatus.BAD_REQUEST),
    PASSWORD_CONFIRMATION_MISMATCH(HttpStatus.BAD_REQUEST),
    PASSWORD_POLICY_VIOLATION(HttpStatus.BAD_REQUEST),
    NEW_PASSWORD_MUST_BE_DIFFERENT(HttpStatus.BAD_REQUEST),
    DAILY_PLAN_NOT_FOUND(HttpStatus.NOT_FOUND),
    DAILY_PLAN_VERSION_NOT_FOUND(HttpStatus.NOT_FOUND),
    DAILY_PLAN_DRAFT_EXISTS(HttpStatus.CONFLICT),
    DAILY_PLAN_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND),
    DAILY_PLAN_ITEM_HAS_PROGRESS(HttpStatus.CONFLICT),
    DAILY_PLAN_EXISTS(HttpStatus.CONFLICT),
    CONFLICT(HttpStatus.CONFLICT),
    TOO_MANY_REQUESTS(HttpStatus.TOO_MANY_REQUESTS),
    INVALID_PLAN_TRANSITION(HttpStatus.CONFLICT),
    DAILY_PLAN_LOCKED(HttpStatus.CONFLICT),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_FILE_TYPE(HttpStatus.BAD_REQUEST),
    FILE_TOO_LARGE(HttpStatus.PAYLOAD_TOO_LARGE),
    FILE_STORAGE_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    AI_PROVIDER_NOT_FOUND(HttpStatus.NOT_FOUND),
    AI_PROVIDER_CODE_EXISTS(HttpStatus.CONFLICT),
    AI_PROVIDER_IN_USE(HttpStatus.CONFLICT),
    AI_PROVIDER_CREDENTIAL_NOT_FOUND(HttpStatus.NOT_FOUND),
    AI_PROVIDER_CREDENTIAL_REQUIRED(HttpStatus.CONFLICT),
    AI_PROVIDER_CONFIG_NOT_FOUND(HttpStatus.NOT_FOUND),
    AI_PROVIDER_INVALID_CONFIGURATION(HttpStatus.BAD_REQUEST),
    AI_PROVIDER_DEFAULT_REQUIRED(HttpStatus.CONFLICT),
    AI_PROVIDER_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
    AI_EXECUTION_NOT_FOUND(HttpStatus.NOT_FOUND),
    AI_GENERATION_FAILED(HttpStatus.BAD_GATEWAY),
    AI_OUTPUT_INVALID(HttpStatus.BAD_GATEWAY),
    QUIZ_NOT_FOUND(HttpStatus.NOT_FOUND),
    QUIZ_ALREADY_SUBMITTED(HttpStatus.CONFLICT),
    QUIZ_ANSWERS_INCOMPLETE(HttpStatus.BAD_REQUEST),
    QUIZ_ANSWER_DUPLICATE(HttpStatus.BAD_REQUEST),
    QUIZ_QUESTION_NOT_FOUND(HttpStatus.BAD_REQUEST),
    QUIZ_OPTION_INVALID(HttpStatus.BAD_REQUEST),
    WEAK_TOPIC_NOT_FOUND(HttpStatus.NOT_FOUND),
    INSUFFICIENT_COMPLETED_TASKS(HttpStatus.BAD_REQUEST);

    private final HttpStatus status;

    ErrorCode(HttpStatus status) {
        this.status = status;
    }

    public HttpStatus status() {
        return status;
    }
}
