package com.codegym.aiplanning.common.exception;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
    VALIDATION_FAILED(HttpStatus.BAD_REQUEST),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    INVALID_GOOGLE_CREDENTIAL(HttpStatus.UNAUTHORIZED),
    INVALID_SESSION(HttpStatus.UNAUTHORIZED),
    REFRESH_IN_PROGRESS(HttpStatus.CONFLICT),
    AUTHENTICATION_REQUIRED(HttpStatus.UNAUTHORIZED),
    SESSION_EXPIRED(HttpStatus.UNAUTHORIZED),
    ACCESS_DENIED(HttpStatus.FORBIDDEN),
    ACCOUNT_DISABLED(HttpStatus.FORBIDDEN),
    ADMIN_ACCOUNT_PROTECTED(HttpStatus.CONFLICT),
    GOOGLE_ACCOUNT_LINK_REQUIRED(HttpStatus.CONFLICT),
    GOOGLE_AUTH_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
    COURSE_NOT_FOUND(HttpStatus.NOT_FOUND),
    COURSE_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT),
    CLASS_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT),
    INVALID_CLASS_CODE(HttpStatus.BAD_REQUEST),
    INVALID_CLASS_NAME(HttpStatus.BAD_REQUEST),
    INVALID_CLASS_DATES(HttpStatus.BAD_REQUEST),
    INVALID_STATUS_TRANSITION(HttpStatus.BAD_REQUEST),
    CLASS_NOT_FOUND(HttpStatus.NOT_FOUND),
    MODULE_NOT_FOUND(HttpStatus.NOT_FOUND),
    MODULE_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT),
    CONCURRENT_MODIFICATION(HttpStatus.CONFLICT),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND),
    CURRENT_PASSWORD_INCORRECT(HttpStatus.BAD_REQUEST),
    PASSWORD_CONFIRMATION_MISMATCH(HttpStatus.BAD_REQUEST),
    PASSWORD_POLICY_VIOLATION(HttpStatus.BAD_REQUEST),
    NEW_PASSWORD_MUST_BE_DIFFERENT(HttpStatus.BAD_REQUEST),
    CONFLICT(HttpStatus.CONFLICT),
    TOO_MANY_REQUESTS(HttpStatus.TOO_MANY_REQUESTS),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR);

    private final HttpStatus status;

    ErrorCode(HttpStatus status) {
        this.status = status;
    }

    public HttpStatus status() {
        return status;
    }
}
