package com.codegym.aiplanning.entity.audit;

public enum AuditEventAction {
    PROFILE_SETUP_COMPLETED,
    PROFILE_UPDATED,
    ROADMAP_ONBOARDING_STARTED,
    ROADMAP_ONBOARDING_UPDATED,
    ROADMAP_ONBOARDING_COMPLETED,
    PASSWORD_CHANGED,
    PASSWORD_CHANGE_FAILED,
    PASSWORD_RESET_REQUESTED,
    DAILY_PLAN_CREATED,
    DAILY_PLAN_UPDATED,
    PROGRESS_RECORDED
}
