package com.codegym.aiplanning.entity.audit;

public enum AuditEventAction {
    PROFILE_SETUP_COMPLETED,
    PROFILE_UPDATED,
    ROADMAP_ONBOARDING_STARTED,
    ROADMAP_ONBOARDING_UPDATED,
    ROADMAP_ONBOARDING_COMPLETED,
    ROADMAP_CREATED,
    ROADMAP_VERSION_CREATED,
    ROADMAP_ITEM_CREATED,
    ROADMAP_ITEM_UPDATED,
    ROADMAP_ITEM_DELETED,
    ROADMAP_VERSION_ACTIVATED,
    PASSWORD_CHANGED,
    PASSWORD_CHANGE_FAILED,
    PASSWORD_RESET_REQUESTED,
    DAILY_PLAN_CREATED,
    DAILY_PLAN_VERSION_CREATED,
    DAILY_PLAN_VERSION_ACTIVATED,
    DAILY_PLAN_UPDATED,
    PROGRESS_RECORDED,
    ROADMAP_VERSION_GENERATED_BY_AI,
    ROADMAP_VERSION_REGENERATED_BY_AI
}
