package com.codegym.aiplanning.entity.audit;

public enum AuditEventAction {
    USER_CREATED,
    USER_UPDATED,
    USER_STATUS_CHANGED,
    USER_DISABLED,
    PASSWORD_CHANGED,
    PASSWORD_CHANGE_FAILED,
    PASSWORD_RESET_REQUESTED,
    STUDENT_ADDED_TO_CLASS,
    STUDENT_REMOVED_FROM_CLASS,
    STUDENT_TRANSFERRED_CLASS,
    INSTRUCTOR_ASSIGNED_TO_CLASS,
    INSTRUCTOR_REMOVED_FROM_CLASS,
    MODULE_PROGRESS_CREATED,
    MODULE_PROGRESS_UPDATED,
    COURSE_CREATED,
    COURSE_UPDATED,
    COURSE_DEACTIVATED
}
